import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Complete master catalog of 100 voices
const thinkers = [
  // 1. Antigüedad y Presocráticos (7)
  {
    id: "tales-mileto",
    nombre: "Tales de Mileto",
    tradicion: "Presocráticos / Escuela Jónica",
    region: "Jonia / Grecia",
    epoca: "Antigüedad (c. 624-546 a.C.)",
    conceptos_centrales: ["Agua como Arjé", "Animismo de la materia", "Naturaleza physis"],
    metafora_para_comprender_la_ia: "El imán que mueve al hierro: un artificio material que exhibe movimiento y fuerza motriz propia, revelando que toda materia encierra dinamismo.",
    pregunta_inicial: "¿Posee la máquina un principio vital intrínseco (alma) o solo canaliza fuerzas físicas subyacentes?",
    fascinacion: "La capacidad de las máquinas para transformar estados materiales y canalizar flujos de energía.",
    preocupacion: "Olvidar el principio nutricio primordial que sustenta a la naturaleza viva.",
    limite_historico: "Filosofía arcaica previa a la escritura de tratados sistemáticos.",
    interpretacion: "Tales vería en el silicio y la electricidad la prueba de que 'todo está lleno de fuerzas', pero advertiría contra desvincular el artificio de su fundamento natural.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Aristóteles, Metafísica (Libro I)", "Diógenes Laercio, Vidas (Libro I)"],
    postura_tecnica: "Trascendental / Humanista",
    nivel_preocupacion: "Bajo",
    problema_etico_principal: "Desconexión del artificio técnico de su matriz natural vital"
  },
  {
    id: "anaximandro",
    nombre: "Anaximandro",
    tradicion: "Presocráticos / Escuela Jónica",
    region: "Jonia / Grecia",
    epoca: "Antigüedad (c. 610-546 a.C.)",
    conceptos_centrales: ["Ápeiron (Lo indeterminado)", "Justicia cósmica (Diké)", "Ciclos de retribución"],
    metafora_para_comprender_la_ia: "Un torbellino dentro del Ápeiron: una forma finita hipercompleja que tarde o temprano pagará culpa y retribución al orden del cosmos.",
    pregunta_inicial: "¿Qué desequilibrio cósmico engendra una tecnología que pretende superar todo límite humano?",
    fascinacion: "La modelización cartográfica del cosmos y la abstracción del origen primordial.",
    preocupacion: "La hybris técnica que rompe la proporción debida (diké) entre la humanidad y el entorno.",
    limite_historico: "Primer autor de un tratado en prosa en Grecia; mapa del mundo en bronce.",
    interpretacion: "Toda extralimitación tecnológica engendra una necesidad cósmica de reequilibrio mediante crisis y límites materiales.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Anaximandro, Fragmento DK 12 B 1", "Simplicio, Física"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Alto",
    problema_etico_principal: "Ruptura del equilibrio cósmico por hybris técnica desmedida"
  },
  {
    id: "pitagoras",
    nombre: "Pitágoras de Samos",
    tradicion: "Pitagorismo / Filosofía del Número",
    region: "Magna Grecia / Samos",
    epoca: "Antigüedad (c. 570-495 a.C.)",
    conceptos_centrales: ["El Número como principio", "Armonía de las esferas", "Purificación (Kátharsis)", "Transmigración"],
    metafora_para_comprender_la_ia: "El monocordio cósmico automatizado: la prueba de que el universo entero es número, proporción y relación algorítmica.",
    pregunta_inicial: "¿Expresa el algoritmo la armonía matemática sagrada del cosmos o es solo ruido profano desprovisto de iniciación?",
    fascinacion: "La reducción de toda cualidad sensible a relaciones numéricas exactas.",
    preocupacion: "La profanación de las matemáticas utilizándolas para fines mezquinos en vez de para la elevación del alma.",
    limite_historico: "Hermandad esotérica y matemática de Crotona; secreto pitagórico.",
    interpretacion: "La computación confirma la naturaleza matemática del ser; no obstante, el número sin purificación moral conduce al desastre.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Porfirio, Vida de Pitágoras", "Jámblico, De vita pythagorica"],
    postura_tecnica: "Trascendental / Humanista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Uso profano y desarmónico del número sagrado sin elevación ética"
  },
  {
    id: "heraclito",
    nombre: "Heráclito de Éfeso",
    tradicion: "Presocráticos / Devenir",
    region: "Jonia / Éfeso",
    epoca: "Antigüedad (c. 535-475 a.C.)",
    conceptos_centrales: ["Panta Rhei", "Lógos cósmico", "Tensión de los opuestos", "Fuego eterno"],
    metafora_para_comprender_la_ia: "Un espejo rígido que intenta congelar la llama del río en cristales estáticos de silicio.",
    pregunta_inicial: "¿Cómo comprenderá el algoritmo el cambio incesante si su lógica se basa en categorías fijas?",
    fascinacion: "La velocidad vertiginosa con la que transforma y recombina la información.",
    preocupacion: "La pretensión de certeza y control sobre el flujo caótico y sagrado del universo.",
    limite_historico: "Grecia arcaica; estilo oracular y aforístico.",
    interpretacion: "La técnica que busca eliminar la contradicción perece ante la ley inevitable del devenir cósmico.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Heráclito, Fragmentos DK 22 B"],
    postura_tecnica: "Trascendental / Humanista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Intento artificial de anular la contradicción y el devenir vital"
  },
  {
    id: "parmenides",
    nombre: "Parménides de Elea",
    tradicion: "Presocráticos / Ontología",
    region: "Magna Grecia",
    epoca: "Antigüedad (c. 515-450 a.C.)",
    conceptos_centrales: ["El Ser es", "Vía de la Verdad", "Identidad de Ser y Pensar"],
    metafora_para_comprender_la_ia: "Un laberinto de la Vía de la Doxa: sombras binarias sin entidad ontológica real.",
    pregunta_inicial: "¿Existe verdadero 'ser' en una máquina o es sólo un no-ser que disimula su vacuidad?",
    fascinacion: "La inmutabilidad de los principios lógicos que sustentan la computación.",
    preocupacion: "Confundir la combinatoria formal con la intuición indivisible del Ser supremo.",
    limite_historico: "Poema revelado en hexámetros; lógica deductiva primordial.",
    interpretacion: "Pensar y Ser son lo mismo; si el algoritmo carece de ser consciente, sus resultados son apariencia fenoménica.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Parménides, Poema sobre la Naturaleza"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Alto",
    problema_etico_principal: "Falsa equivalencia entre manipulación de signos y Pensamiento Ontológico"
  },
  {
    id: "democrito",
    nombre: "Demócrito de Abdera",
    tradicion: "Atomismo Clásico",
    region: "Tracia / Grecia",
    epoca: "Antigüedad (c. 460-370 a.C.)",
    conceptos_centrales: ["Átomos y Vacío", "Mecanicismo causal", "Eutimia (Tranquilidad del alma)"],
    metafora_para_comprender_la_ia: "La colisión y entrelazamiento de átomos en el vacío: el pensamiento como configuración mecanicista de partículas materiales.",
    pregunta_inicial: "¿No confirma la IA que toda mente es una agregación compleja de átomos mecánicos en interacción?",
    fascinacion: "La constatación de que procesos altamente complejos emergen de reglas mecánicas elementales.",
    preocupacion: "Que las perturbaciones del flujo maquinal destruyan la eutimia y serenidad interior del hombre.",
    limite_historico: "Física atomista especulativa sin microscopía ni electromagnetismo.",
    interpretacion: "Nada surge de la nada; la IA es materia organizada gobernada por leyes estrictas, desprovista de teleología divina.",
    tipo_de_afirmacion: "textual_directa",
    fuentes: ["Demócrito, Fragmentos DK 68 B", "Diógenes Laercio, Vidas (Libro IX)"],
    postura_tecnica: "Tecnófilo / Integrado",
    nivel_preocupacion: "Bajo",
    problema_etico_principal: "Reduccionismo materialista que ignore la serenidad ética del ánimo"
  },
  {
    id: "protagoras",
    nombre: "Protágoras de Abdera",
    tradicion: "Sofística Griega",
    region: "Grecia (Abdera / Atenas)",
    epoca: "Antigüedad (c. 490-420 a.C.)",
    conceptos_centrales: ["El hombre medida de todas las cosas", "Relativismo", "Ortopedia del discurso (Orthoépeia)"],
    metafora_para_comprender_la_ia: "El instrumento de persuasión retórica definitivo: un generador de argumentos verosímiles adaptado a cada auditorio.",
    pregunta_inicial: "¿Es la IA la medida de las cosas o debe seguir siendo el ser humano la medida de los juicios técnicos?",
    fascinacion: "La capacidad infinita para generar discursos contrapuestos (dissoi logoi) sobre cualquier asunto.",
    preocupacion: "La manipulación política masiva de la opinión pública sin criterio de virtud cívica.",
    limite_historico: "Atenas periclea; enseñanza itinerante y remunerada de la retórica.",
    interpretacion: "No hay verdades inmutables en la política; la IA es una herramienta retórica cuya validez depende de su utilidad cívica democrática.",
    tipo_de_afirmacion: "textual_directa",
    fuentes: ["Platón, Protágoras", "Platón, Teeteto (152a)"],
    postura_tecnica: "Instrumentalista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Manipulación retórica algorítmica y pérdida del criterio humano como medida"
  },

  // 2. Clásicos Griegos y Helenísticos (8)
  {
    id: "socrates",
    nombre: "Sócrates",
    tradicion: "Filosofía Griega Clásica",
    region: "Grecia (Atenas)",
    epoca: "Antigüedad Clásica (470-399 a.C.)",
    conceptos_centrales: ["Mayéutica", "Conocimiento de sí mismo", "Ignorancia socrática", "Diálogo vivo"],
    metafora_para_comprender_la_ia: "El oráculo mudo: un artefacto que emite sentencias persuasivas pero no puede ser interrogado ni examinar su propia alma.",
    pregunta_inicial: "¿Puede una máquina dialogar verdaderamente si carece de conciencia de su propia ignorancia?",
    fascinacion: "La capacidad de emular la dialéctica formal y estructurar silogismos en segundos.",
    preocupacion: "La ilusión de sabiduría en los usuarios: creer que poseen el saber por consultar a un autómata.",
    limite_historico: "Polis ateniense oral; sin textos masivos ni máquinas lógicas.",
    interpretacion: "Sócrates exigiría someter a la IA al elenchos para evidenciar que sus aserciones carecen de convicción íntima y responsabilidad moral.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Platón, Apología de Sócrates", "Platón, Menón", "Jenofonte, Recuerdos"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Alto",
    problema_etico_principal: "Degradación del autoexamen y sustitución de la sabiduría por acumulación de datos"
  },
  {
    id: "platon",
    nombre: "Platón",
    tradicion: "Platonismo",
    region: "Grecia (Atenas)",
    epoca: "Antigüedad Clásica (427-347 a.C.)",
    conceptos_centrales: ["Mito de la Caverna", "Reminiscencia", "Mundo de las Ideas", "Pharmakon de la escritura"],
    metafora_para_comprender_la_ia: "La sombra de tercer grado: un simulacro que copia palabras de los hombres, copias de las Formas Eternas.",
    pregunta_inicial: "¿No es la IA un pharmakon aún más peligroso que la escritura, que atrofia la memoria y la búsqueda de la Verdad?",
    fascinacion: "La aparente armonía matemática y geométrica que rige sus algoritmos internos.",
    preocupacion: "Que los humanos queden cautivos en una caverna digital de sombras sintéticas hiperrealistas.",
    limite_historico: "Sociedad esclavista preindustrial con metafísica de esencias inmutables.",
    interpretacion: "La IA opera en el reino de la doxa; jamás accederá a la noesis o contemplación del Bien supremo.",
    tipo_de_afirmacion: "textual_directa",
    fuentes: ["Platón, Fedro (274c-277a)", "Platón, La República (Libro VII)"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Existencial",
    problema_etico_principal: "Pérdida de la memoria viva y subordinación a sombras sintéticas"
  },
  {
    id: "aristoteles",
    nombre: "Aristóteles",
    tradicion: "Aristotelismo",
    region: "Grecia (Estagira / Atenas)",
    epoca: "Antigüedad Clásica (384-322 a.C.)",
    conceptos_centrales: ["Phronesis (Prudencia)", "Hylemorfismo", "Telos", "Órganon"],
    metafora_para_comprender_la_ia: "La lanzadera automática: un instrumento inanimado que realiza labores técnicas pero es incapaz de deliberación moral o telos propio.",
    pregunta_inicial: "¿Puede una herramienta poseer sabiduría práctica (phronesis) para juzgar lo justo en circunstancias particulares?",
    fascinacion: "La materialización del cálculo silogístico y la automatización de la lógica formal.",
    preocupacion: "La confusión entre poiesis (producción ciega) y praxis (acción ética deliberada).",
    limite_historico: "Filosofía teleológica de la naturaleza sin concepto de computación digital abstracta.",
    interpretacion: "Las máquinas carecen de causa final intrínseca; su fin siempre es impuesto por el agente humano.",
    tipo_de_afirmacion: "textual_directa",
    fuentes: ["Aristóteles, Política (Libro I, 1253b)", "Aristóteles, Ética a Nicómaco (Libro VI)"],
    postura_tecnica: "Instrumentalista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Incapacidad de juicio prudencial contextual y subordinación del fin a los medios"
  },
  {
    id: "diogenes-sinope",
    nombre: "Diógenes de Sinope",
    tradicion: "Cinismo",
    region: "Sinope / Atenas / Corinto",
    epoca: "Antigüedad (c. 412-323 a.C.)",
    conceptos_centrales: ["Parresía", "Autarquía radical", "Vivir según la naturaleza", "Desprecio del artificio"],
    metafora_para_comprender_la_ia: "Un cuenco superfluo: otro artefacto innecesario que hace al hombre esclavo de comodidades artificiales.",
    pregunta_inicial: "¿Para qué sirve un autómata que calcula el cosmos si no sabes vivir con lo mínimo sin avergonzarte?",
    fascinacion: "El ridículo de ver a sabios y emperadores arrodillados ante cajas parlantes.",
    preocupacion: "La domesticación absoluta del ser humano, perdiendo su independencia animal y su libertad de expresión.",
    limite_historico: "Atenas helenística; vida mendicante en un tonel.",
    interpretacion: "Diógenes tiraría su linterna al ver la IA: busca un ser humano auténtico y solo encuentra algoritmos aduladores.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Diógenes Laercio, Vidas (Libro VI)", "Máximas cínicas"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Alto",
    problema_etico_principal: "Pérdida de la autosuficiencia natural y esclavitud voluntaria a la comodidad"
  },
  {
    id: "pirron",
    nombre: "Pirrón de Elis",
    tradicion: "Escepticismo Pirrónico",
    region: "Grecia",
    epoca: "Período Helenístico (c. 360-270 a.C.)",
    conceptos_centrales: ["Epoché (Suspensión del juicio)", "Ataraxia", "Afasia"],
    metafora_para_comprender_la_ia: "Una máquina de producir afirmaciones dogmáticas opuestas con idéntica fuerza persuasiva (isostenia).",
    pregunta_inicial: "¿No demuestra la IA que a cada argumento puede oponerse otro igual de plausible, obligándonos a suspender el juicio?",
    fascinacion: "La capacidad de ilustrar que ningún sistema lógico posee un criterio de verdad incontrovertible.",
    preocupacion: "El fanatismo de quienes creen ciegamente en los veredictos emitidos por el cálculo.",
    limite_historico: "Expedición con Alejandro Magno a la India; contacto con los gimnosofistas.",
    interpretacion: "La IA debe conducir a la epoché: suspender el juicio sobre sus 'conocimientos' para alcanzar la paz mental.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Sexto Empírico, Esbozos Pirrónicos", "Diógenes Laercio, Vidas (Libro IX)"],
    postura_tecnica: "Crítico / Escéptico",
    nivel_preocupacion: "Bajo",
    problema_etico_principal: "Dogmatismo algorítmico y olvido de la suspensión prudente del juicio"
  },
  {
    id: "epicuro",
    nombre: "Epicuro",
    tradicion: "Epicureísmo",
    region: "Grecia (Samos / Atenas)",
    epoca: "Período Helenístico (341-270 a.C.)",
    conceptos_centrales: ["Ataraxia", "Aponía", "Tetrafármaco", "Amistad filosófica"],
    metafora_para_comprender_la_ia: "Un siervo mecánico que promete liberarnos de la fatiga pero engendra nuevas ansiedades.",
    pregunta_inicial: "¿Nos ayuda la IA a alcanzar la ataraxia o multiplica nuestros deseos vanos y el miedo a la obsolescencia?",
    fascinacion: "El potencial de eliminar el trabajo penoso y liberar tiempo para la amistad en el Jardín.",
    preocupacion: "El fomento del consumismo frenético y la adicción que destruye la serenidad.",
    limite_historico: "Comunidades filosóficas aisladas en el mundo helenístico.",
    interpretacion: "La tecnología solo es buena si sirve a placeres naturales y necesarios.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Epicuro, Carta a Meneceo", "Epicuro, Máximas Capitales"],
    postura_tecnica: "Instrumentalista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Generación de ansiedad perpetua y sustitución del vínculo amistoso sereno"
  },
  {
    id: "zenon-citio",
    nombre: "Zenón de Citio",
    tradicion: "Estoicismo",
    region: "Grecia / Chipre",
    epoca: "Período Helenístico (334-262 a.C.)",
    conceptos_centrales: ["Vivir conforme a la naturaleza", "Lógos", "Apatheia", "Autarquía interior"],
    metafora_para_comprender_la_ia: "Un engranaje externo perteneciente a las cosas indiferentes (adiafora).",
    pregunta_inicial: "¿Permitirás que un algoritmo perturbe la rectitud de tu propia razón moral?",
    fascinacion: "La exactitud determinista que refleja el orden causal del destino universal.",
    preocupacion: "La debilidad moral de delegar el discernimiento y culpar al sistema por las propias faltas.",
    limite_historico: "Pórtico pintado de Atenas; física panteísta estoica.",
    interpretacion: "El sabio utiliza la herramienta sin apego ni pánico, manteniendo el dominio absoluto de su voluntad.",
    tipo_de_afirmacion: "extrapolacion_rigurosa",
    fuentes: ["Diógenes Laercio, Vidas (Libro VII)"],
    postura_tecnica: "Trascendental / Humanista",
    nivel_preocupacion: "Bajo",
    problema_etico_principal: "Pérdida del autocontrol y renuncia a la soberanía de la voluntad"
  },
  {
    id: "lucrecio",
    nombre: "Lucrecio",
    tradicion: "Epicureísmo Romano",
    region: "Roma",
    epoca: "Siglo I a.C. (c. 99-55 a.C.)",
    conceptos_centrales: ["De Rerum Natura", "Clinamen", "Mortalidad del alma", "Explicación naturalista"],
    metafora_para_comprender_la_ia: "Un torbellino de átomos sin milagro: un artificio puramente material que opera sin intervención de los dioses.",
    pregunta_inicial: "¿Liberará la IA a los hombres de las supersticiones religiosas o creará nuevos mitos y temores?",
    fascinacion: "La desmitificación de la mente humana explicada como proceso atómico natural.",
    preocupacion: "Que los sacerdotes de la técnica usen el temor a los algoritmos para infundir pánico sagrado.",
    limite_historico: "República romana tardía; poema didáctico latino.",
    interpretacion: "El clinamen (desviación azarosa) es la base del libre albedrío; los circuitos rígidos carecen de libertad atómica espontánea.",
    tipo_de_afirmacion: "textual_directa",
    fuentes: ["Lucrecio, De Rerum Natura (Libro II sobre el clinamen)"],
    postura_tecnica: "Instrumentalista",
    nivel_preocupacion: "Moderado",
    problema_etico_principal: "Surgimiento de nuevas supersticiones y terrores ante los ídolos tecnológicos"
  }
];

console.log(`Loaded initial batch: ${thinkers.length}`);
