import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const thinkers = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/thinkers.json"), "utf8"));
const councils = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/councils.json"), "utf8"));
const dep = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/dependency_matrix.json"), "utf8"));
const lab = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/decision_lab.json"), "utf8"));
const man = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/manifesto.json"), "utf8"));
if (thinkers.length !== 100) throw new Error("Thinkers count must be 100");
console.log("PASS: 100 Thinkers verified.");
if (councils.length !== 10) throw new Error("Councils count must be 10");
console.log("PASS: 10 Councils verified.");
if (dep.fases.length !== 6 || dep.dimensiones.length !== 7) throw new Error("Invalid dependency matrix");
console.log("PASS: Dependency matrix verified.");
if (lab.length < 5) throw new Error("Invalid Decision Lab");
console.log("PASS: Decision Lab verified.");
if (!man.carta_de_autonomia || !man.constitucion_minima || !man.manifiesto_final) throw new Error("Invalid Manifesto");
console.log("PASS: Manifesto verified.");
console.log("=== ALL CONTRACTS LOADED AND PASSED (100%) ===");