const fs = require('fs');
const path = require('path');
const rootDir = path.join(__dirname, '..');

const compLines = [
  'import React from "react";',
  'import { X, ArrowRightLeft, Sparkles, ShieldAlert, BookOpen, AlertTriangle, Compass } from "lucide-react";',
  '',
  'export default function ThinkerCompareModal({ thinkerA, thinkerB, onClose }) {',
  '  if (!thinkerA || !thinkerB) return null;',
  '',
  '  return (',
  '    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink-900/60 backdrop-blur-sm overflow-y-auto animate-fadeIn">',
  '      <div className="pergamino-card w-full max-w-5xl max-h-[90vh] rounded-2xl shadow-2xl overflow-y-auto border border-parchment-300 relative" role="dialog">',
  '        {/* Header */}',
  '        <div className="sticky top-0 bg-parchment-100/95 backdrop-blur border-b border-parchment-300 p-6 flex items-center justify-between z-10">',
  '          <div className="flex items-center space-x-2">',
  '            <ArrowRightLeft className="w-5 h-5 text-terracotta-600" />',
  '            <h3 className="text-xl font-serif font-bold text-ink-900">Ágora de Confrontación Dialéctica</h3>',
  '          </div>',
  '          <button onClick={onClose} className="p-2 rounded-full hover:bg-parchment-200 text-ink-600 hover:text-ink-900 transition-all"><X className="w-6 h-6" /></button>',
  '        </div>',
  '',
  '        {/* Compare Grid */}',
  '        <div className="p-6 sm:p-8 space-y-6">',
  '          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">',
  '            {/* Thinker A */}',
  '            <div className="p-6 bg-white rounded-2xl border border-parchment-300 shadow-sm space-y-4">',
  '              <div className="space-y-1 border-b border-parchment-200 pb-3">',
  '                <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-terracotta-500/10 text-terracotta-700">{thinkerA.tradicion}</span>',
  '                <h4 className="text-2xl font-serif font-bold text-ink-900 pt-1">{thinkerA.nombre}</h4>',
  '                <span className="text-xs text-ink-500 block">{thinkerA.region} · {thinkerA.epoca}</span>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-terracotta-700">Metáfora para comprender la IA</span>',
  '                <p className="text-sm font-serif italic text-ink-800 bg-parchment-100 p-3 rounded-lg border border-parchment-200">“{thinkerA.metafora_para_comprender_la_ia}”</p>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-ink-500">Postura & Preocupación</span>',
  '                <div className="flex flex-wrap gap-2 text-xs font-semibold">',
  '                  <span className="px-2 py-0.5 bg-parchment-200 rounded">{thinkerA.postura_tecnica}</span>',
  '                  <span className="px-2 py-0.5 bg-red-500/10 text-red-700 rounded border border-red-500/20">Preocupación: {thinkerA.nivel_preocupacion}</span>',
  '                </div>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-terracotta-700">Preocupación Crítica</span>',
  '                <p className="text-xs text-ink-700 font-reading leading-relaxed">{thinkerA.preocupacion}</p>',
  '              </div>',
  '',
  '              <div className="space-y-1 pt-2 border-t border-parchment-200">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-ink-500">Fuentes Canónicas</span>',
  '                <ul className="text-xs text-ink-600 list-disc list-inside">{thinkerA.fuentes.map((f, i) => <li key={i}>{f}</li>)}</ul>',
  '              </div>',
  '            </div>',
  '',
  '            {/* Thinker B */}',
  '            <div className="p-6 bg-white rounded-2xl border border-parchment-300 shadow-sm space-y-4">',
  '              <div className="space-y-1 border-b border-parchment-200 pb-3">',
  '                <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-bronze-500/10 text-bronze-700">{thinkerB.tradicion}</span>',
  '                <h4 className="text-2xl font-serif font-bold text-ink-900 pt-1">{thinkerB.nombre}</h4>',
  '                <span className="text-xs text-ink-500 block">{thinkerB.region} · {thinkerB.epoca}</span>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-bronze-700">Metáfora para comprender la IA</span>',
  '                <p className="text-sm font-serif italic text-ink-800 bg-parchment-100 p-3 rounded-lg border border-parchment-200">“{thinkerB.metafora_para_comprender_la_ia}”</p>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-ink-500">Postura & Preocupación</span>',
  '                <div className="flex flex-wrap gap-2 text-xs font-semibold">',
  '                  <span className="px-2 py-0.5 bg-parchment-200 rounded">{thinkerB.postura_tecnica}</span>',
  '                  <span className="px-2 py-0.5 bg-red-500/10 text-red-700 rounded border border-red-500/20">Preocupación: {thinkerB.nivel_preocupacion}</span>',
  '                </div>',
  '              </div>',
  '',
  '              <div className="space-y-1">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-bronze-700">Preocupación Crítica</span>',
  '                <p className="text-xs text-ink-700 font-reading leading-relaxed">{thinkerB.preocupacion}</p>',
  '              </div>',
  '',
  '              <div className="space-y-1 pt-2 border-t border-parchment-200">',
  '                <span className="text-xs uppercase font-bold tracking-wider text-ink-500">Fuentes Canónicas</span>',
  '                <ul className="text-xs text-ink-600 list-disc list-inside">{thinkerB.fuentes.map((f, i) => <li key={i}>{f}</li>)}</ul>',
  '              </div>',
  '            </div>',
  '          </div>',
  '        </div>',
  '',
  '        {/* Footer */}',
  '        <div className="bg-parchment-200/60 border-t border-parchment-300 px-6 py-4 flex justify-end">',
  '          <button onClick={onClose} className="px-5 py-2 rounded-lg bg-ink-900 text-white text-sm font-medium hover:bg-ink-800 transition-all">Cerrar Confrontación</button>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}'
];

fs.writeFileSync(path.join(rootDir, 'src', 'components', 'ThinkerCompareModal.jsx'), compLines.join('\n'), 'utf8');
console.log('Created ThinkerCompareModal.jsx');

// 2. Update Atlas.jsx to include Compare Mode
const atlasLines = [
  'import React, { useState, useMemo } from "react";',
  'import { Search, Filter, Sparkles, MapPin, Calendar, ShieldAlert, Compass, Eye, ArrowRightLeft, Check } from "lucide-react";',
  'import thinkersData from "../../data/thinkers.json";',
  'import ThinkerModal from "./ThinkerModal.jsx";',
  'import ThinkerCompareModal from "./ThinkerCompareModal.jsx";',
  '',
  'export default function Atlas() {',
  '  const [search, setSearch] = useState("");',
  '  const [selectedTradition, setSelectedTradition] = useState("all");',
  '  const [selectedStance, setSelectedStance] = useState("all");',
  '  const [selectedConcern, setSelectedConcern] = useState("all");',
  '  const [activeThinker, setActiveThinker] = useState(null);',
  '  const [compareList, setCompareList] = useState([]);',
  '  const [showCompareModal, setShowCompareModal] = useState(false);',
  '',
  '  const traditions = useMemo(() => {',
  '    const set = new Set(thinkersData.map((t) => t.tradicion));',
  '    return ["all", ...Array.from(set)];',
  '  }, []);',
  '',
  '  const stances = ["all", "Trascendental / Humanista", "Crítico / Escéptico", "Instrumentalista", "Tecnófilo / Integrado", "Descolonial / Comunitario"];',
  '  const concerns = ["all", "Bajo", "Moderado", "Alto", "Existencial"];',
  '',
  '  const filteredThinkers = useMemo(() => {',
  '    return thinkersData.filter((t) => {',
  '      const matchesSearch =',
  '        t.nombre.toLowerCase().includes(search.toLowerCase()) ||',
  '        t.conceptos_centrales.some((c) => c.toLowerCase().includes(search.toLowerCase())) ||',
  '        t.metafora_para_comprender_la_ia.toLowerCase().includes(search.toLowerCase()) ||',
  '        t.region.toLowerCase().includes(search.toLowerCase());',
  '',
  '      const matchesTradition = selectedTradition === "all" || t.tradicion === selectedTradition;',
  '      const matchesStance = selectedStance === "all" || t.postura_tecnica === selectedStance;',
  '      const matchesConcern = selectedConcern === "all" || t.nivel_preocupacion === selectedConcern;',
  '',
  '      return matchesSearch && matchesTradition && matchesStance && matchesConcern;',
  '    });',
  '  }, [search, selectedTradition, selectedStance, selectedConcern]);',
  '',
  '  const toggleCompare = (e, thinker) => {',
  '    e.stopPropagation();',
  '    if (compareList.some((x) => x.id === thinker.id)) {',
  '      setCompareList((prev) => prev.filter((x) => x.id !== thinker.id));',
  '    } else {',
  '      if (compareList.length >= 2) {',
  '        setCompareList([compareList[1], thinker]);',
  '      } else {',
  '        setCompareList((prev) => [...prev, thinker]);',
  '      }',
  '    }',
  '  };',
  '',
  '  return (',
  '    <div className="space-y-8 py-6">',
  '      <div className="text-center max-w-3xl mx-auto space-y-2">',
  '        <h2 className="text-3xl sm:text-4xl font-serif font-bold text-ink-900">Atlas de Pensadores</h2>',
  '        <p className="text-sm sm:text-base text-ink-600 font-reading">',
  '          Explora la polifonía de exactamente 100 voces ante la técnica, filtrando por tradición o comparándolas cara a cara.',
  '        </p>',
  '      </div>',
  '',
  '      {/* Comparison Floating Action Bar */}',
  '      {compareList.length > 0 && (',
  '        <div className="sticky top-24 z-30 max-w-2xl mx-auto bg-ink-900 text-white p-4 rounded-2xl shadow-xl border border-terracotta-500/40 flex items-center justify-between animate-fadeIn">',
  '          <div className="flex items-center space-x-2 text-xs">',
  '            <ArrowRightLeft className="w-4 h-4 text-terracotta-400" />',
  '            <span>Confrontar: <strong>{compareList.map((t) => t.nombre).join(" vs. ")}</strong> ({compareList.length}/2)</span>',
  '          </div>',
  '          <div className="flex items-center space-x-2">',
  '            <button onClick={() => setCompareList([])} className="text-xs text-ink-300 hover:text-white px-2 py-1">Limpiar</button>',
  '            {compareList.length === 2 && (',
  '              <button onClick={() => setShowCompareModal(true)} className="px-3 py-1.5 rounded-lg bg-terracotta-600 text-white text-xs font-bold shadow hover:bg-terracotta-700 transition-all">',
  '                Abrir Comparador',
  '              </button>',
  '            )}',
  '          </div>',
  '        </div>',
  '      )}',
  '',
  '      {/* Search & Filter Controls */}',
  '      <div className="pergamino-card p-6 rounded-2xl shadow-sm space-y-4 max-w-6xl mx-auto border border-parchment-300">',
  '        <div className="relative">',
  '          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-ink-400" />',
  '          <input',
  '            type="text"',
  '            value={search}',
  '            onChange={(e) => setSearch(e.target.value)}',
  '            placeholder="Buscar por pensador, concepto clave, región o metáfora..."',
  '            className="w-full pl-12 pr-4 py-3 rounded-xl bg-white border border-parchment-300 text-ink-900 placeholder:text-ink-400 focus:outline-none focus:border-terracotta-500 focus:ring-1 focus:ring-terracotta-500 font-reading text-sm"',
  '          />',
  '        </div>',
  '',
  '        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-medium">',
  '          <div>',
  '            <label className="block text-ink-500 uppercase tracking-wider mb-1 font-bold">Tradición Filosófica</label>',
  '            <select',
  '              value={selectedTradition}',
  '              onChange={(e) => setSelectedTradition(e.target.value)}',
  '              className="w-full p-2.5 rounded-lg bg-white border border-parchment-300 text-ink-900 focus:outline-none focus:border-terracotta-500"',
  '            >',
  '              <option value="all">Todas las tradiciones ({thinkersData.length})</option>',
  '              {traditions.filter((x) => x !== "all").map((trad) => (',
  '                <option key={trad} value={trad}>{trad}</option>',
  '              ))}',
  '            </select>',
  '          </div>',
  '',
  '          <div>',
  '            <label className="block text-ink-500 uppercase tracking-wider mb-1 font-bold">Postura ante la Técnica</label>',
  '            <select',
  '              value={selectedStance}',
  '              onChange={(e) => setSelectedStance(e.target.value)}',
  '              className="w-full p-2.5 rounded-lg bg-white border border-parchment-300 text-ink-900 focus:outline-none focus:border-terracotta-500"',
  '            >',
  '              <option value="all">Todas las posturas</option>',
  '              {stances.filter((x) => x !== "all").map((st) => (',
  '                <option key={st} value={st}>{st}</option>',
  '              ))}',
  '            </select>',
  '          </div>',
  '',
  '          <div>',
  '            <label className="block text-ink-500 uppercase tracking-wider mb-1 font-bold">Nivel de Preocupación</label>',
  '            <select',
  '              value={selectedConcern}',
  '              onChange={(e) => setSelectedConcern(e.target.value)}',
  '              className="w-full p-2.5 rounded-lg bg-white border border-parchment-300 text-ink-900 focus:outline-none focus:border-terracotta-500"',
  '            >',
  '              <option value="all">Todos los niveles</option>',
  '              {concerns.filter((x) => x !== "all").map((lvl) => (',
  '                <option key={lvl} value={lvl}>{lvl}</option>',
  '              ))}',
  '            </select>',
  '          </div>',
  '        </div>',
  '',
  '        <div className="flex items-center justify-between pt-2 border-t border-parchment-200 text-xs text-ink-600">',
  '          <span>Mostrando <strong>{filteredThinkers.length}</strong> de <strong>{thinkersData.length}</strong> pensadores</span>',
  '          {(search || selectedTradition !== "all" || selectedStance !== "all" || selectedConcern !== "all") && (',
  '            <button',
  '              onClick={() => {',
  '                setSearch("");',
  '                setSelectedTradition("all");',
  '                setSelectedStance("all");',
  '                setSelectedConcern("all");',
  '              }}',
  '              className="text-terracotta-600 hover:underline font-semibold"',
  '            >',
  '              Limpiar filtros',
  '            </button>',
  '          )}',
  '        </div>',
  '      </div>',
  '',
  '      {/* Thinkers Cards Grid */}',
  '      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">',
  '        {filteredThinkers.map((t) => {',
  '          const isCompared = compareList.some((x) => x.id === t.id);',
  '          return (',
  '            <div',
  '              key={t.id}',
  '              onClick={() => setActiveThinker(t)}',
  '              className={`pergamino-card p-6 rounded-2xl hover:border-terracotta-500 hover:shadow-lg transition-all cursor-pointer flex flex-col justify-between space-y-4 group ${\n' +
  '                isCompared ? "ring-2 ring-terracotta-600 bg-terracotta-500/5" : ""\n' +
  '              }`}',
  '            >',
  '              <div className="space-y-3">',
  '                <div className="flex items-start justify-between gap-2">',
  '                  <div>',
  '                    <span className="text-xs font-semibold text-terracotta-700 bg-terracotta-500/10 px-2 py-0.5 rounded-full">',
  '                      {t.tradicion}',
  '                    </span>',
  '                    <h3 className="text-xl font-serif font-bold text-ink-900 group-hover:text-terracotta-600 transition-colors pt-1">',
  '                      {t.nombre}',
  '                    </h3>',
  '                  </div>',
  '                  <button',
  '                    onClick={(e) => toggleCompare(e, t)}',
  '                    title={isCompared ? "Quitar de comparación" : "Añadir para comparar"}',
  '                    className={`p-1.5 rounded-lg border text-xs flex items-center space-x-1 transition-all ${\n' +
  '                      isCompared\n' +
  '                        ? "bg-terracotta-600 text-white border-terracotta-700"\n' +
  '                        : "bg-white border-parchment-300 text-ink-600 hover:border-terracotta-500"\n' +
  '                    }`}',
  '                  >',
  '                    {isCompared ? <Check className="w-3.5 h-3.5" /> : <ArrowRightLeft className="w-3.5 h-3.5" />}',
  '                  </button>',
  '                </div>',
  '',
  '                <div className="text-xs text-ink-500 space-y-1">',
  '                  <div className="flex items-center space-x-1.5"><MapPin className="w-3.5 h-3.5" /><span>{t.region}</span></div>',
  '                  <div className="flex items-center space-x-1.5"><Calendar className="w-3.5 h-3.5" /><span>{t.epoca}</span></div>',
  '                </div>',
  '',
  '                <p className="text-xs sm:text-sm font-serif italic text-ink-800 line-clamp-2 bg-parchment-200/50 p-2.5 rounded-lg border border-parchment-200">',
  '                  “{t.metafora_para_comprender_la_ia}”',
  '                </p>',
  '              </div>',
  '',
  '              <div className="pt-3 border-t border-parchment-200 flex items-center justify-between text-xs text-ink-500">',
  '                <div className="flex flex-wrap gap-1">',
  '                  {t.conceptos_centrales.slice(0, 2).map((c, i) => (',
  '                    <span key={i} className="px-2 py-0.5 bg-white border border-parchment-300 rounded text-[11px] font-medium">{c}</span>',
  '                  ))}',
  '                </div>',
  '                <span className="flex items-center space-x-1 text-terracotta-600 font-semibold group-hover:translate-x-1 transition-transform">',
  '                  <span>Dossier</span>',
  '                  <Eye className="w-3.5 h-3.5" />',
  '                </span>',
  '              </div>',
  '            </div>',
  '          );',
  '        })}',
  '      </div>',
  '',
  '      {/* Thinker Modal */}',
  '      {activeThinker && (',
  '        <ThinkerModal thinker={activeThinker} onClose={() => setActiveThinker(null)} />',
  '      )}',
  '',
  '      {/* Compare Modal */}',
  '      {showCompareModal && compareList.length === 2 && (',
  '        <ThinkerCompareModal',
  '          thinkerA={compareList[0]}',
  '          thinkerB={compareList[1]}',
  '          onClose={() => setShowCompareModal(false)}',
  '        />',
  '      )}',
  '    </div>',
  '  );',
  '}'
];

fs.writeFileSync(path.join(rootDir, 'src', 'components', 'Atlas.jsx'), atlasLines.join('\n'), 'utf8');
console.log('Updated Atlas.jsx with Compare Modal integration.');